swagger: '2.0'
info:
  title: MicrosoftOffice Files Parser
  description: Custom connector for parsing Word and Excel documents.
  version: '1.0'
host: ssnotes.azurewebsites.net
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /apps/parser/word.php:
    post:
      responses:
        200:
          description: Text extracted successfully
          schema:
            type: object
            properties:
              message:
                type: string
                example: Text extracted successfully
                description: Result message from the API
              text:
                type: string
                example: Cloud
                description: Extracted text content
            required:
              - message
              - text
      summary: Parse Word Document
      description: Parses a Word document from base64 content.
      operationId: Word_Document
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              $content-type:
                type: string
                description: Content-Type of the document
                title: ''
              base64$content:
                type: string
                description: Base64 encoded Word document content
                title: ''
            required:
              - $content-type
              - base64$content
  /apps/parser/excel.php:
    post:
      responses:
        200:
          description: Excel parsing response containing worksheet data in arrays
          schema:
            type: object
            properties:
              Worksheets:
                type: array
                description: List of all sheet names in the response
                items:
                  type: string
            required:
              - Worksheets
            additionalProperties:
              type: array
              description: 2D array of strings representing sheet data rows and columns
              items:
                type: array
                items:
                  type: string
      summary: Excel_Spreadsheet
      description: Excel_Spreadsheet
      operationId: Excel_Spreadsheet
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              $content-type:
                type: string
                description: content-type
                title: content-type
              $filename:
                type: string
                description: filename with extension
                title: $filename
              base64$content:
                type: string
                description: base64$content
                title: base64$content
            required:
              - base64$content
              - $content-type
              - $filename
definitions: {}
parameters: {}
responses: {}
securityDefinitions: {}
security: []
tags: []